server:
  servlet:
    context-path: /api
spring:
  application:
    name: app
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: carpag
      port: 27017
      host: localhost
      auto-index-creation: true
      uri: mongodb://root:root@localhost:27017/carpag
